### PR TITLE
Initial UI for User Registration

### PR DESCRIPTION
**Pull request by janrebpol**
**OVERVIEW**

Designed using CSS

**SNIPPETS**

Screenshot 2024-04-05 164517

### CODE REVIEW

**Comment by sunkenquest** [comment]
Please do not include `node_modules` when pushing your changes. Add it to `.gitignore` if needed.

**Comment by janrebpol** [comment]
> Collaborator

resolved

**Comment by janrebpol** [comment]
**OVERVIEW**

Final UI for Registration (Mobile Responsive) - Tailwind CSS

**SNIPPETS**
image

**Review by sunkenquest — APPROVED** [review]
GEFN 🚀

**Pull request merged**
